services:
  team1pwn1:
    build: .
    hostname: team1pwn1
    ports:
      - "10102:1337"
      - "10122:22"
    restart: always
  team2pwn1:
    build: .
    hostname: team2pwn1
    ports:
      - "10202:1337"
      - "10222:22"
    restart: always
