services:
  team1_web1:
    build: .
    hostname: web1
    ports:
    - "10101:80"
    - "10121:22"
  team2_web1:
    build: .
    hostname: web1
    ports:
    - "10201:80"
    - "10221:22"