admin:
  username: forcad
  password: forcad

game:
  mode: classic
  round_time: 20
  start_time: 2024-10-25 09:10:00
  timezone: Etc/UTC

  default_score: 2500
  flag_lifetime: 1
  game_hardness: 10.0
  inflation: true

tasks:
  - checker: web1/checker.py
    checker_timeout: 10
    checker_type: hackerdom
    gets: 2
    name: web1
    places: 2
    puts: 2

  - checker: web2/checker.py
    checker_timeout: 10
    checker_type: hackerdom
    gets: 2
    name: web2
    places: 2
    puts: 2

teams:
  - ip: 192.168.0.1
    name: "Team 1"

  - ip: 192.168.0.2
    name: "Team 2 (highlighted)"
    highlighted: true
